### ISSUE TITLE
Bug: (i think) Local editable installs don't seem to work

### ISSUE THREAD

**Issue by peterschutt** [piccolo-orm/piccolo_admin#232]
Trying to debug an app that depends on this library, normally I would do something like this in `pyproject.toml`:

```python
[tool.poetry.dependencies]
...
piccolo_admin = { extras = ["all"], path = "../piccolo_admin", develop=true }
```

However I get an error like this:

```
  PackageInfoError

  Unable to determine package info for path: /home/peter/PycharmProjects/piccolo_admin
  
  Fallback egg_info generation failed.
  
  Command ['/tmp/tmpa6kh9fkl/.venv/bin/python', 'setup.py', 'egg_info'] errored with the following return code 1, and output: 
  Traceback (most recent call last):
    File "/home/peter/PycharmProjects/piccolo_admin/setup.py", line 10, in <module>
      from piccolo_admin.version import __VERSION__ as VERSION
    File "/home/peter/PycharmProjects/piccolo_admin/piccolo_admin/__init__.py", line 1, in <module>
      from .endpoints import FormConfig, create_admin
    File "/home/peter/PycharmProjects/piccolo_admin/piccolo_admin/endpoints.py", line 15, in <module>
      from fastapi import FastAPI, File, Form, UploadFile
  ModuleNotFoundError: No module named 'fastapi'
```

Which is caused by the import from `.version` in `__init__.py` alongside imports from `.endpoints`. The `.endpoints` module imports from dependencies that don't yet exist as the `setup()` function has yet to be called in `setup.py` when the version is imported.

Obviously not an issue for your workflow as seems to have been like that for a while, so would understand a "wontfix", but figured I would raise.

A simple way to repo is to do `$ python -m pip install -e .` from within the `piccolo_admin` repo root.

**Comment by peterschutt** [comment]
Too good! I'll try now.
